class CommentaryData {
  static const List<String> winningSmall = [
    "¡Uy! Ganando por un pelo. 😅",
    "No se confíen, que esto vira. 🔄",
    "Ventaja mínima, presión máxima. ⚡",
    "Un respiro... pero pequeño. 🤏",
    "¡Cuidado con la remontada! 🚀",
    "Están sudando frío, pero van ganando. 😰",
    "Apretado, pero arriba. 👆",
    "¡Mantengan el paso! 🏃‍♂️",
    "Casi empate, pero no. 🚫",
    "Un dominó mal puesto y adiós ventaja. 🎲",
    "¡Ojo al piojo! 🧐",
    "Están ganando, pero no convencen. 🤨",
    "¿Suerte o habilidad? 🤔",
    "Por ahora, los reyes. 👑",
    "¡No bajen la guardia! 🛡️",
    "Esto está más tenso que cuerda de violín. 🎻",
    "Ganando por la mínima, sufriendo al máximo. 😫",
    "Unos puntitos de oro. 💰",
    "A nada del empate. ⚠️",
    "¡Agárrense que vienen curvas! 🏎️",
    "Sonriendo, pero nerviosos. 😬",
    "¡Sigan sumando! ➕",
    "Poquito a poco se llena el jarro. 🏺",
    "No canten victoria todavía. 🎤",
    "El miedo no anda en burro. 🫏",
    "¡Concentración total! 🧠",
    "Un error y chau ventaja. 👋",
    "Jugando con fuego. 🔥",
    "Si se puede, cero bulla. 🔥",
    "¡Vamos que se puede ampliar! 💪",
    "Raspando la victoria. 🧀",
    "Ta’ arriba pero no te duerma.🚫",
    "Ta’ picando suave… no aflojes.💪",
    "Con calma que va llegando la vaina.🧘",
    "Así e’, punto a punto como la gente.👥",
    "Ta’ dominando sin hacer ruido.🎮", 
    "Eso e’ lo tuyo, pasito a pasito.",
    "No te guille, pero ta’ arriba.🚨",
    "Ta’ controlando la vuelta. 🏃"
  ];

  static const List<String> winningBig = [
    "¡Les están dando una paliza! 😂",
    "¿Dónde está el otro equipo? 👻",
    "Sencillo, como quitarle un dulce a un niño. 🍭",
    "¡Abuso! ¡Llamen a la policía! 🚓",
    "Esto ya parece un monólogo. 🎤",
    "¡Piedad, por favor! 🙏",
    "Están jugando solos. 🧍‍♂️",
    "Demasiado fácil. 😎",
    "¡Aplanadora en marcha! 🚜",
    "Ya pueden ir pidiendo la revancha. 🔄",
    "¡Qué baile les están dando! 💃",
    "Dominio total y absoluto. 🌍",
    "¡No hay competencia! 🚫",
    "Les pasaron el trapo. 🧹",
    "¡Están intratables! 😤",
    "¿Trajeron pañuelos para los perdedores? 🤧",
    "¡Masacre en la mesa! ⚔️",
    "Clase magistral de dominó. 🎓",
    "¡Imparables! 🚀",
    "Esto huele a zapatero. 👞",
    "¡Qué paliza histórica! 📚",
    "¿Se rinden ya? 🏳️",
    "Jugando a otro nivel. 🆙",
    "¡Despegue vertical! 🛫",
    "Ni con milagros los alcanzan. ✨",
    "¡Son los dueños del patio! 🏠",
    "¡Qué manera de sumar! 📈",
    "¡Al parecer estas Jugando solo!😎📈",
    "Están en racha divina. 😇",
    "¡Aplausos para los líderes! 👏",
    "Victoria a la vista. 🔭",
  ];

  static const List<String> winning10 = [
    "Diez arriba y contando… ta’ fluyendo.",
    "Diez puntos no e’ cualquiera, ta’ manejando.",
    "Ta’ sacando ventaja sin mucho sonido.",
    "Diez puntos y subiendo, ta’ haciendo la tarea.",
    "Por diez se siente, pero falta juego todavía.",
    "Eso e’ control total, ventaja de diez.",
    "Diez puntos que hablan solos.",
  ];

  static const List<String> winningGeneral = [
    "Vamos ganando. Mantén el ritmo. 😎",
    "Buen juego, sigan así. 👍",
    "Sumando y gozando. 🥳",
    "El liderato es suyo. 🏆",
    "Controlando la partida. 🎮",
    "Paso firme hacia la victoria. 👣",
    "La estrategia está funcionando. ♟️",
    "¡Eso es! No aflojen. 🔨",
    "Arriba en el marcador. ⬆️",
    "Viento en popa. ⛵",
    "Todo bajo control. 👮‍♂️",
    "Se respira victoria. 🌬️",
    "Jugando bonito. ✨",
    "La mesa es suya. 🍽️",
    "¡Qué bien se ve ese marcador! 👀",
    "Liderando con estilo. 🕶️",
    "¡Dale que tú sabes! 🤜🤛",
    "Punto a punto. 📍",
    "Construyendo el triunfo. 🏗️",
    "¡Esa es la actitud! 💯",
    "Juego sólido. 🧱",
    "Sin prisa pero sin pausa. 🐢",
    "Dominando el dominó. 🎲",
    "¡Buen trabajo equipo! 🤝",
    "La balanza se inclina a su favor. ⚖️",
    "Disfruten la ventaja. 🍹",
    "¡A seguir sumando! ➕",
    "El camino al éxito. 🛣️",
    "Jugadas maestras. 🎨",
    "¡Qué calidad! ⭐",
    "Ta’ metiendo mano con elegancia. 🏆",
    "Va ganando cómodo, sin estrés. 😌",
    "Tiene la pámpara prendía en la cancha. 🔥",
    "Se está dejando sentir. 💪",
    "Este juego ta’ bajando pa’ su lado. 📈",
    "La vuelta le salió, ta’ arriba. ✔️",
    "Ta’ manejando el juego con flow. 🎨",
    "Lo estás manejando como un patrón. 👑"
  ];

  // 20 – 29 puntos
  static const List<String> winning20 = [
    "Veinte arriba… eso es una pela organizada.",
    "A veinte puntos, ya eso parece práctica.",
    "Veinte arriba, y sin sudar mucho.",
    "El otro lado ta’ recogiendo los pedazos.",
    "Manejo clínico, veinte puntos de diferencia.",
    "Nadie sabe cómo frenar la vuelta.",
    "Veinte puntos y contando, feo pa’ la foto.",
    "Ta’ limpiando la cancha, veinte arriba."
  ];

  static const List<String> losingSmall = [
    "¡Vamos! Solo faltan unos puntos. 🤏",
    "Están ahí mismo, ¡no se rindan! 💪",
    "Un empujoncito y los pasan. 🏎️",
    "La diferencia es nada. 0️⃣",
    "¡Apretó el zapato! 👞",
    "Esto se voltea en un dos por tres. 🔄",
    "¡Ánimo! Están en la pelea. 🥊",
    "Respire profundo y juegue. 🧘‍♂️",
    "Casi, casi. 👌",
    "No está muerto quien pelea. 🧟",
    "¡A remontar se ha dicho! 🗣️",
    "Un buen cierre y listo. 🔒",
    "La suerte cambia rápido. 🍀",
    "Tiemblan los de arriba. 🥶",
    "¡Presión, presión! 💣",
    "Les están pisando los talones. 👠",
    "¡No tiren la toalla! 🧖‍♂️",
    "Esto no se acaba hasta que se acaba. 🏁",
    "¡Vamos con todo! 🚀",
    "Fe en la remontada. 🙏",
    "Están sudando los líderes. 😅",
    "¡A ponerle corazón! ❤️",
    "Jugada a jugada. 🎲",
    "¡Despierten que se puede! ⏰",
    "La victoria está cerca. 📍",
    "¡A descontar! 📉",
    "Un error de ellos y ¡zas! ⚡",
    "¡Fuerza equipo! 🏋️‍♂️",
    "Están a tiro de piedra. 🪨",
    "¡Vamos que se puede! 🙌",
    "¿Y ese coro? Paga’ pa’ perder. 💸",
    "Juega porque pagó, no porque puede. 😂",
    "Dio pa’ la liga infantil hoy. 🧒",
    "Se ve que ta’ jugando por hobby. 🏀",
    "E’ mejor que se siente y aplauda. 👏",
    "Parece que vino sin desayunar. 🍽️🚫",
    "Lo trajeron pa’ relleno. 📦",
    "Está en el juego pero no en la tabla. 📉"
  ];

  // 40 – 49 puntos
  static const List<String> winning40 = [
    "Cuarenta arriba… apaguen la luz.",
    "Cuarenta puntos, eso e’ carnicería deportiva.",
    "Demolición controlada, cuarenta puntos.",
    "Ni la banca los salva, cuarenta arriba.",
    "Eso duele hasta verlo.",
    "La vaina se salió de control, cuarenta arriba.",
    "Coma deportivo, cuarenta abajo.",
    "Cuarenta puntos… no hay forma humana."
  ];

  // 50+ puntos (Paliza)
  static const List<String> winning50 = [
    "Cincuenta arriba… récord de humillación.",
    "Trauma colectivo, cincuenta puntos.",
    "Que venga el ministerio público.",
    "Cincuenta puntos… esto debería ser ilegal.",
    "Falta de respeto deportiva, cincuenta arriba.",
    "Funeral deportivo, cincuenta puntos.",
    "Eso es cierre de liga completo.",
    "Cinco contra cero, porque del otro lado no se ve nadie."
  ];

  static const List<String> losingBig = [
    "Nos están dando duro... ¡Pero la remontada será épica! 💪",
    "¿Alguien anotó las placas del camión? 🚚",
    "¡Llamen a la ambulancia! 🚑",
    "Esto duele... 🤕",
    "¡A levantarse! Todavía queda juego. 🌅",
    "La esperanza es lo último que se pierde. 🕯️",
    "¡Necesitamos un milagro! ✨",
    "¿Cambiamos de pareja? 💔",
    "¡Qué pela nos están dando! 🍌",
    "¡S.O.S! 🆘",
    "Respiren... es solo un juego (mentira, ganen). 🤥",
    "¡Vamos a despertar! ☕",
    "Nos tienen de hijos. 👶",
    "¡A remar contra la corriente! 🚣‍♂️",
    "¿Y si barajamos de nuevo? 🃏",
    "¡Qué paliza! Pero volveremos. 🔙",
    "Hoy no es nuestro día... ¿o sí? 📅",
    "¡Ánimo, que peores cosas han pasado! 🌪️",
    "A mal tiempo, buena cara. 🤡",
    "¡Vamos a ponerle picante! 🌶️",
    "¿Dónde está la defensa? 🛡️",
    "¡Auxilio! 🏳️",
    "Nos están pasando el rolo. 🚜",
    "¡A sacudirse esa mala racha! 🐕",
    "Todavía respiro, todavía juego. 🫁",
    "¡Vamos, no sean zapateros! 👞",
    "El dominó da revancha. 🔄",
    "¡A jugar con honor! 🎖️",
    "Aunque perdamos, ¡que sea con estilo! 🕺",
    "¡Despierten leones! 🦁",
  ];

  static const List<String> losingGeneral = [
    "Concentración. Todavía podemos ganar. 🧠",
    "No se den por vencidos. 🚫",
    "A pensar cada jugada. 🤔",
    "La paciencia es clave. 🔑",
    "¡Arriba ese ánimo! 🎈",
    "Ajusten la estrategia. 🔧",
    "¡Vamos a recuperarnos! ❤️‍🩹",
    "Paso a paso se llega. 👣",
    "¡Sí se puede! 🙌",
    "Cabeza fría, dominó caliente. 🧊🔥",
    "El juego no ha terminado. 🛑",
    "¡A luchar cada punto! ⚔️",
    "Confíen en su pareja. 🤝",
    "¡Vamos equipo! 📣",
    "A darlo vuelta. 🔄",
    "¡Más atención! 👁️",
    "Jueguen inteligente. 🤓",
    "La suerte es loca. 🤪",
    "¡A sacar la casta! 🐂",
    "No bajen los brazos. 💪",
    "Todavía hay tiempo. ⏳",
    "El que persevera alcanza. 🏃‍♂️",
    "¡Vamos a sumar! ➕",
    "No regalen nada. 🎁",
    "¡A pelear! 🥊",
    "Sorprendan al rival. 👻",
    "¡Enfoque! 📷",
    "La remontada es posible. 🌈",
    "¡Vamos guerreros! 🛡️",
    "A cambiar la historia. 📖",
  ];

  static const List<String> tie = [
    "¡Empate técnico! Esto está que arde. 🔥",
    "Tablas. Nadie cede ni un centímetro. 📏",
    "¡Qué tensión! 😬",
    "Iguales... ¿quién parpadea primero? 👁️",
    "Como empezar de cero. 0️⃣",
    "¡Duelo de titanes! ⚔️",
    "Ni para ti, ni para mí. 🤝",
    "¡Qué parejo está esto! ⚖️",
    "¡Empate! A romperse la cabeza. 🤯",
    "Nadie quiere perder. 🙅‍♂️",
  ];
  
  static const List<String> startHigh = [
    "¡BOOM! 💥 ¡Qué comienzo explosivo! Más de 60 de una. 🚀",
    "¡Arrancaron con todo! 🔥 ¡Tiemblen rivales!",
    "¡Eso es entrar por la puerta grande! 🚪✨",
    "¡Madre mía! ¿Venían con prisa? 🏃💨",
    "¡Abusadores! 60+ para empezar. 👮‍♂️",
    "¡Qué mano increíble! 🙌",
    "¡Alerta de paliza! 🚨 Empezaron volando.",
    "¡Sin piedad desde el inicio! 😈",
    "¡Espectacular! 🌟",
    "¡Cátedra de dominó en la primera mano! 🎓",
  ];
  static const List<String> comeback = [
    "¡Comenzó el ingenio a moler caña! 🚜🎋",
    "¡Despertó el gigante! 🦍",
    "¡Se prendió esto! 🔥",
    "¡Ahora es que empieza el juego! 🎬",
    "¡Cuidado que vienen con todo! ⚠️",
  ];

  static const List<String> payerTaunt = [
    "Esta mano la paga tu jugador... ya sabes quién. 💸",
    "¡Prepara la billetera! 💳",
    "Alguien hoy duerme afuera... 🛋️",
    "Esa ficha te costó caro. 📉",
    "¡Qué dolor! 🤕",
  ];
}
